spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 23514181521
    url: jdbc:mysql://localhost:3306/hys_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 3000